export async function onRequest(context) {
        const { request, env } = context;

            const corsHeaders = {
                    "Access-Control-Allow-Origin": "*",
                            "Access-Control-Allow-Methods": "GET, OPTIONS",
                                    "Access-Control-Allow-Headers": "Content-Type, Authorization",
                                            "Content-Type": "application/json",
                                                };

                                                    if (request.method === "OPTIONS") {
                                                            return new Response(null, { headers: corsHeaders });
                                                                }

                                                                    try {
                                                                            // Extrair o token do cabeçalho de Autorização enviado pelo index.html
                                                                                    const authHeader = request.headers.get("Authorization");
                                                                                            if (!authHeader || !authHeader.startsWith("Bearer ")) {
                                                                                                        return new Response(JSON.stringify({ error: "Token não fornecido" }), {
                                                                                                                        status: 401,
                                                                                                                                        headers: corsHeaders,
                                                                                                                                                    });
                                                                                                                                                            }

                                                                                                                                                                    const token = authHeader.replace("Bearer ", "");

                                                                                                                                                                            // Validar se o token de sessão existe e está associado a um membro ativo
                                                                                                                                                                                    const sessao = await env.DB.prepare(
                                                                                                                                                                                                `SELECT s.usuario_id, s.expira_em, m.code, m.name, m.email, m.status
                                                                                                                                                                                                             FROM sessoes s
                                                                                                                                                                                                                          JOIN club_members m ON m.id = s.usuario_id
                                                                                                                                                                                                                                       WHERE s.token = ? AND s.tipo_usuario = 'membro'`
                                                                                                                                                                                                                                               )
                                                                                                                                                                                                                                                           .bind(token)
                                                                                                                                                                                                                                                                       .first();

                                                                                                                                                                                                                                                                               if (!sessao) {
                                                                                                                                                                                                                                                                                           return new Response(JSON.stringify({ error: "Sessão inválida" }), {
                                                                                                                                                                                                                                                                                                           status: 401,
                                                                                                                                                                                                                                                                                                                           headers: corsHeaders,
                                                                                                                                                                                                                                                                                                                                       });
                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                       // Se a sessão expirou, remove ela do banco automaticamente
                                                                                                                                                                                                                                                                                                                                                               if (new Date(sessao.expira_em) < new Date()) {
                                                                                                                                                                                                                                                                                                                                                                           await env.DB.prepare(`DELETE FROM sessoes WHERE token = ?`).bind(token).run();
                                                                                                                                                                                                                                                                                                                                                                                       return new Response(JSON.stringify({ error: "Sessão expirada" }), {
                                                                                                                                                                                                                                                                                                                                                                                                       status: 401,
                                                                                                                                                                                                                                                                                                                                                                                                                       headers: corsHeaders,
                                                                                                                                                                                                                                                                                                                                                                                                                                   });
                                                                                                                                                                                                                                                                                                                                                                                                                                           }

                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Devolve os dados do perfil limpos para serem carregados na tela preta do membro
                                                                                                                                                                                                                                                                                                                                                                                                                                                           return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       JSON.stringify({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       id: sessao.usuario_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       codigo: sessao.code,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       nome: sessao.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       email: sessao.email,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       status: sessao.status === "active" ? "Ativo" : "Inativo",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               { status: 200, headers: corsHeaders }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return new Response(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               JSON.stringify({ error: error.message }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           { status: 500, headers: corsHeaders }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
}