export async function onRequestPost(context) {
    try {
        const { request, env } = context;

            if (!env.DB) {
                  return new Response(JSON.stringify({ error: "Banco de dados não configurado." }), { 
                          status: 500,
                                  headers: { "Content-Type": "application/json" }
                                        });
                                            }

                                                // 1. 🔒 BLOCO DE SEGURANÇA: Verifica quem está tentando alterar a senha
                                                    const cookieHeader = request.headers.get("Cookie") || "";
                                                        const cookies = Object.fromEntries(cookieHeader.split(";").map(c => c.trim().split("=")));
                                                            const token = cookies["auth_token"];

                                                                if (!token) {
                                                                      return new Response(JSON.stringify({ error: "Acesso negado. Faça login primeiro." }), { 
                                                                              status: 401,
                                                                                      headers: { "Content-Type": "application/json" }
                                                                                            });
                                                                                                }

                                                                                                    // Busca a sessão ativa no banco de dados para validar
                                                                                                        const sessao = await env.DB.prepare(
                                                                                                              "SELECT * FROM sessoes WHERE token = ? AND datetime(expira_em) > datetime('now') LIMIT 1"
                                                                                                                  ).bind(token).first();

                                                                                                                      if (!sessao) {
                                                                                                                            return new Response(JSON.stringify({ error: "Sessão inválida ou expirada." }), { 
                                                                                                                                    status: 401,
                                                                                                                                            headers: { "Content-Type": "application/json" }
                                                                                                                                                  });
                                                                                                                                                      }

                                                                                                                                                          // 2. Captura as senhas enviadas pelo formulário
                                                                                                                                                              const { senhaAtual, novaSenha } = await request.json();

                                                                                                                                                                  if (!senhaAtual || !novaSenha) {
                                                                                                                                                                        return new Response(JSON.stringify({ error: "A senha atual e a nova senha são obrigatórias." }), { 
                                                                                                                                                                                status: 400,
                                                                                                                                                                                        headers: { "Content-Type": "application/json" }
                                                                                                                                                                                              });
                                                                                                                                                                                                  }

                                                                                                                                                                                                      const usuarioId = sessao.usuario_id;
                                                                                                                                                                                                          const tipoUsuario = sessao.tipo_usuario; // 'membro', 'parceiro' ou 'admin'

                                                                                                                                                                                                              // 3. Atualização condicional baseada no tipo de usuário logado
                                                                                                                                                                                                                  if (tipoUsuario === "membro") {
                                                                                                                                                                                                                        // Verifica a senha antiga na tabela club_members
                                                                                                                                                                                                                              const membro = await env.DB.prepare('SELECT senha_hash FROM club_members WHERE id = ?').bind(usuarioId).first();
                                                                                                                                                                                                                                    if (!membro || membro.senha_hash !== senhaAtual) {
                                                                                                                                                                                                                                            return new Response(JSON.stringify({ error: "A senha atual está incorreta." }), { status: 400 });
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                        // Grava a nova senha
                                                                                                                                                                                                                                                              await env.DB.prepare('UPDATE club_members SET senha_hash = ? WHERE id = ?').bind(novaSenha, usuarioId).run();

                                                                                                                                                                                                                                                                  } else if (tipoUsuario === "parceiro") {
                                                                                                                                                                                                                                                                        // Verifica a senha antiga na tabela parceiros
                                                                                                                                                                                                                                                                              const parceiro = await env.DB.prepare('SELECT senha_hash FROM parceiros WHERE id = ?').bind(usuarioId).first();
                                                                                                                                                                                                                                                                                    if (!parceiro || parceiro.senha_hash !== senhaAtual) {
                                                                                                                                                                                                                                                                                            return new Response(JSON.stringify({ error: "A senha atual está incorreta." }), { status: 400 });
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                        // Grava a nova senha
                                                                                                                                                                                                                                                                                                              await env.DB.prepare('UPDATE parceiros SET senha_hash = ? WHERE id = ?').bind(novaSenha, usuarioId).run();

                                                                                                                                                                                                                                                                                                                  } else if (tipoUsuario === "admin") {
                                                                                                                                                                                                                                                                                                                        // Verifica a senha antiga na tabela administradores
                                                                                                                                                                                                                                                                                                                              const admin = await env.DB.prepare('SELECT senha FROM administradores WHERE id = ?').bind(usuarioId).first();
                                                                                                                                                                                                                                                                                                                                    if (!admin || admin.senha !== senhaAtual) {
                                                                                                                                                                                                                                                                                                                                            return new Response(JSON.stringify({ error: "A senha atual está incorreta." }), { status: 400 });
                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                        // Grava a nova senha
                                                                                                                                                                                                                                                                                                                                                              await env.DB.prepare('UPDATE administradores SET senha = ? WHERE id = ?').bind(novaSenha, usuarioId).run();
                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                      return new Response(JSON.stringify({ success: true, message: "Sua senha foi alterada com sucesso!" }), {
                                                                                                                                                                                                                                                                                                                                                                            status: 200,
                                                                                                                                                                                                                                                                                                                                                                                  headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                        } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                            return new Response(JSON.stringify({ error: "Erro ao alterar a senha: " + error.message }), { 
                                                                                                                                                                                                                                                                                                                                                                                                  status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                        headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                              
}