export async function onRequestPost(context) {
      try {
          const { request, env } = context;

              if (!env.DB) {
                    return new Response(JSON.stringify({ error: "Banco de dados não configurado." }), { 
                            status: 500,
                                    headers: { "Content-Type": "application/json" }
                                          });
                                              }

                                                  // 1. 🔒 BLOCO DE SEGURANÇA: Apenas parceiros logados (estabelecimentos) registram o uso do benefício
                                                      const cookieHeader = request.headers.get("Cookie") || "";
                                                          const cookies = Object.fromEntries(cookieHeader.split(";").map(c => c.trim().split("=")));
                                                              const token = cookies["auth_token"];

                                                                  if (!token) {
                                                                        return new Response(JSON.stringify({ error: "Acesso negado. O estabelecimento precisa estar logado." }), { 
                                                                                status: 401,
                                                                                        headers: { "Content-Type": "application/json" }
                                                                                              });
                                                                                                  }

                                                                                                      const sessao = await env.DB.prepare(
                                                                                                            "SELECT * FROM sessoes WHERE token = ? AND datetime(expira_em) > datetime('now') LIMIT 1"
                                                                                                                ).bind(token).first();

                                                                                                                    if (!sessao || sessao.tipo_usuario !== "parceiro") {
                                                                                                                          return new Response(JSON.stringify({ error: "Apenas parceiros comerciais podem registrar a utilização de benefícios." }), { 
                                                                                                                                  status: 403,
                                                                                                                                          headers: { "Content-Type": "application/json" }
                                                                                                                                                });
                                                                                                                                                    }

                                                                                                                                                        // 2. Captura os dados do benefício e do membro
                                                                                                                                                            const { codigoMembro, valorTransacao, descricaoBeneficio } = await request.json();

                                                                                                                                                                if (!codigoMembro) {
                                                                                                                                                                      return new Response(JSON.stringify({ error: "O código do membro é obrigatório." }), { 
                                                                                                                                                                              status: 400,
                                                                                                                                                                                      headers: { "Content-Type": "application/json" }
                                                                                                                                                                                            });
                                                                                                                                                                                                }

                                                                                                                                                                                                    // 3. Valida se o membro realmente existe e está ativo na tabela 'club_members'
                                                                                                                                                                                                        const membro = await env.DB.prepare(
                                                                                                                                                                                                              "SELECT id, nome, status FROM club_members WHERE codigo = ? LIMIT 1"
                                                                                                                                                                                                                  ).bind(codigoMembro).first();

                                                                                                                                                                                                                      if (!membro) {
                                                                                                                                                                                                                            return new Response(JSON.stringify({ error: "Membro não encontrado." }), { 
                                                                                                                                                                                                                                    status: 404,
                                                                                                                                                                                                                                            headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                          if (membro.status !== "ativo") {
                                                                                                                                                                                                                                                                return new Response(JSON.stringify({ error: "Este membro está inativo e não pode usar o clube no momento." }), { 
                                                                                                                                                                                                                                                                        status: 403,
                                                                                                                                                                                                                                                                                headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                              // 4. ⚠️ NOTA FUTURA: Se você criar uma tabela 'historico_beneficios' no schema.sql, 
                                                                                                                                                                                                                                                                                                  // você fará o INSERT dela bem aqui usando: sessao.usuario_id (ID do parceiro) e membro.id (ID do membro).

                                                                                                                                                                                                                                                                                                      return new Response(JSON.stringify({
                                                                                                                                                                                                                                                                                                            success: true,
                                                                                                                                                                                                                                                                                                                  message: "Benefício registrado e validado com sucesso!",
                                                                                                                                                                                                                                                                                                                        transaction: {
                                                                                                                                                                                                                                                                                                                                membro: membro.nome,
                                                                                                                                                                                                                                                                                                                                        parceiro_id: sessao.usuario_id,
                                                                                                                                                                                                                                                                                                                                                descricao: descricaoBeneficio || "Desconto aplicado",
                                                                                                                                                                                                                                                                                                                                                        valor: valorTransacao || 0,
                                                                                                                                                                                                                                                                                                                                                                data: new Date().toISOString()
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                          }), {
                                                                                                                                                                                                                                                                                                                                                                                status: 200,
                                                                                                                                                                                                                                                                                                                                                                                      headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                return new Response(JSON.stringify({ error: "Erro ao registrar uso do benefício: " + error.message }), { 
                                                                                                                                                                                                                                                                                                                                                                                                      status: 500,
                                                                                                                                                                                                                                                                                                                                                                                                            headers: { "Content-Type": "application/json" }
                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                  
}